apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: RapidXAPI
  description: The Petstore API
spec:
  type: openapi
  lifecycle: production
  owner: petstore@example.com
  definition:
    $text: https://github.com/KaranS0406/API/blob/main/api.yaml
